version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: event-platform-postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
    name: event-platform-pgdata
